MODULE BAM_CXC

DESCRIPTION IDL bindings for the Color X-ray camera

VERSION 0.1

SOURCE Tom Schoonjans

FUNCTION BAM_CXC_GET_DATA   0 0
FUNCTION BAM_CXC_GET_HITS   0 0
FUNCTION BAM_CXC_GET_ENERGY 0 0
FUNCTION BAM_CXC_GET_MISS   0 0
FUNCTION BAM_CXC_GET_EVENT  0 0
